---
title: "Statistical Burger"
subtitle: "Statistical Learning with Food"
author: "Otho Mantegazza"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    seal: false
    lib_dir: libs
    css: "css/remark.css"
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
knitr::opts_chunk$set(dev = "svglite",
                      echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.height = 6,
                      fig.width = 10)

library(tidyverse)
library(ISLR)
# library(MASS)
library(caret)
library(gridExtra)

theme_set(theme_minimal())

adv <-
  read_csv(here::here("data/adv.csv")) %>% 
  janitor::clean_names() %>% 
  select(-x1)
```


class: title-acc

# Statistical Burger

## Statistical Learning with Food

### Otho

---

class: middle

.big-formula[Y ~ X]

---

class: middle

.big-formula[Y ~ X + ε]

---

class: middle

.big-formula[Y ~ X1 + X2 + ε]

---
class: middle

.big-formula[Y ~ X1 + X2 + X3*X4 ε]

---

```{r}
adv_fit_poly <- lm(sales ~ poly(tv, 2), data = adv)


adv_to_plot <- 
  broom::augment(adv_fit_poly, data = adv)


p <- 
adv_to_plot %>% 
  ggplot(aes(x = tv,
             y = sales)) +
  geom_point(colour = "blue", alpha = .8, size = 2) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  labs(x = "TV advertisment [1000 Units]",
       y = "Product Sales [1000 $]")
  

p
#   geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
#   geom_point(aes(y = .fitted))
```

---

```{r}
guess_1 <- 140
guess_2 <- 95
guess_3 <- 227

annotate_vline <- function(x_val) {
  geom_vline(xintercept = x_val, colour = "red", lty = 2)
}

annotate_x <- function(x_val) {
  annotate(geom = "point", x = x_val, y = 0, colour = "red", shape = 4, size = 6)
}

p_guess <- 
  p +
  annotate_vline(guess_1) +
  annotate_x(guess_1)
  

p_guess
```

---

```{r}
guess_point <- function(x_val, colour = "red") {
  annotate(geom = "point", x = x_val,
           y = predict(adv_fit_poly, newdata = tibble(tv = x_val)),
           colour = colour, size = 6) 
}


p_guess <- p_guess + guess_point(guess_1); p_guess
```

---

```{r}
p_guess <- 
  p_guess +
  annotate_vline(guess_2) +
  annotate_x(guess_2)

p_guess
```

---

```{r}
p_guess <- p_guess + guess_point(guess_2); p_guess
```

---

```{r}
p_guess <- 
  p_guess +
  annotate_vline(guess_3) +
  annotate_x(guess_3)

p_guess
```

---

```{r}
p_guess <- p_guess + guess_point(guess_3); p_guess
```

---

```{r}
p_guess <-
  p_guess +
  geom_smooth(colour = "red",
              method = "lm",
              formula = y ~ poly(x, 2),
              se = FALSE)

p_guess
```

---

```{r}
p
```

---

```{r}
p_out <-
  p +
  annotate_vline(guess_3) +
  annotate_x(guess_3) +
  guess_point(guess_3)


p_out
```

---

```{r}
force_point <- function(x_val,y_val, colour = "red") {
  annotate(geom = "point", x = x_val,
           y = y_val,
           colour = colour, size = 6) 
}

p_out <- 
  p_out +
  annotate_vline(guess_1) +
  annotate_x(guess_1) +
  force_point(x_val = guess_1, y_val = 18.5)

p_out
```

---

```{r}
p_out <- 
  p_out +
  annotate_vline(guess_2) +
  annotate_x(guess_2) +
  force_point(x_val = guess_2, y_val = 25)

p_out
```

---

```{r}
p_out <-
  p_out +
  geom_smooth(colour = "red",
              method = "lm",
              formula = y ~ poly(x, 2),
              se = FALSE)

p_out
```

---

class: middle

.big[All models are wrong, some are useful.]

---

```{r}
adv_fit <- lm(sales ~ tv, data = adv)


adv_to_plot <- 
  broom::augment(adv_fit, data = adv)

p <- 
adv_to_plot %>% 
  ggplot(aes(x = tv,
             y = sales)) +
  geom_point(colour = "blue", alpha = .8, size = 2) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  labs(x = "TV advertisment [1000 Units]",
       y = "Product Sales [1000 $]")

p <- 
  p +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE, colour = "red") +
  annotate(geom = "text", x = 10,
           y = 25, label = "y ~ x",
           vjust = 0, hjust = 0,
           size = 10,
           colour = "red")

p
```

---

```{r}
p <- 
  p +
  geom_segment(aes(xend = ..x..,
                   yend = .fitted),
               size = .3,
               colour = "grey40") 

p
```

---

```{r}
fit_table <-
  adv_fit %>%
  broom::tidy() %>%
  gridExtra::tableGrob(
    theme = ttheme_minimal(base_colour = "blue",
                           base_size = 10)
    ) 


p <- 
  p +
  annotation_custom(grob = fit_table,
                    xmin = 150,
                    ymax = 8)

p
```

---

```{r}
fit_scores <-
  adv_fit %>%
  broom::glance() %>%
  select(1:5) %>% 
  mutate_all(~format(., scientific = TRUE, digits = 2)) %>% 
  gridExtra::tableGrob(
    theme = ttheme_minimal(base_colour = "blue",
                           base_size = 10)
    ) 

p <- 
  p +
  annotation_custom(grob = fit_scores,
                    xmin = 150,
                    ymax = 17)

p
```

---

```{r}
p <- 
adv_to_plot %>% 
  ggplot(aes(x = tv,
             y = .resid)) +
  geom_point(colour = "blue", alpha = .8, size = 2) +
  geom_hline(yintercept = 0, colour = "red") +
  geom_vline(xintercept = 0) +
  geom_segment(aes(xend = ..x..,
                   yend = 0),
               size = .3,
               colour = "grey40") +
  labs(x = "TV advertisment [1000 Units]",
       y = "Product Sales [1000 $]")

p
```

---

```{r}
income <- read_csv(here::here("data/income1.csv")) %>% janitor::clean_names()
```

```{r}
p <- 
income %>% 
  ggplot(aes(x = education,
             y = income)) +
  geom_point(colour = "blue", alpha = .8, size = 2) +
  lims(y = c(11, 90), x = c(9, 22.5)) +
  coord_fixed(ratio = .16)

p 
```

---

```{r}
p +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE, colour = "red")
```

---

```{r}
p +
  geom_smooth(method = "lm", formula = y ~ poly(x, 3), se = FALSE, colour = "red")
```

---

```{r}
p +
  geom_smooth(method = "loess", se = FALSE, span  = .1, colour = "red")
```

---

class: middle

.big[What if the outcome is categorical?]

---

```{r}
data(ISLR::Default)
credit <- Default %>% janitor::clean_names()
```

```{r}
p <- 
  credit %>% 
  ggplot(aes(x = default, y = balance)) +
  geom_violin()

p
```

---

```{r}
p + coord_flip()
```

---

```{r}
credit <- 
  credit %>% as_tibble() %>% 
  mutate(default = as.factor(default) %>% as.numeric(),
         default = default - 1) 



p <- 
  credit %>% 
  ggplot(aes(x = balance, y = default)) +
  geom_text(label = "|", colour = "blue", 
            alpha = .4)

p
```

---

```{r}
fit <- glm(default ~ balance, data = credit, family = "binomial")

p +
  geom_smooth(method = "glm",
              method.args = list(family = "binomial"),
              se = FALSE,
              colour = "red")
```


https://www.kaggle.com/tags/food-and-drink 